### ISSUE TITLE
请求发送请求时创建cache的目的是什么的，都是POST请求

### ISSUE THREAD

**Issue by onesmileme** [lujiajing1126/AliyunLogObjc#11]
NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
    NSString *cachePath = @"AliyunURLCache";
    NSURLCache *cache = [[NSURLCache alloc]initWithMemoryCapacity:16*1024 diskCapacity:256*1024*1024 diskPath:cachePath];
    config.URLCache = cache;
    config.requestCachePolicy = NSURLRequestUseProtocolCachePolicy;

**Comment by lujiajing1126** [comment]
是的，不应该使用缓存

感谢，会去掉这块逻辑

**Comment by lujiajing1126** [comment]
see commit 2823e21
