### ISSUE TITLE
打包IPA报错

### ISSUE THREAD

**Issue by qwerOC** [lujiajing1126/AliyunLogObjc#13]
![2018-04-02 5 25 57](https://user-images.githubusercontent.com/17760059/38194445-27e5e18c-36aa-11e8-82f2-7355be6f1a64.png)

**Comment by lujiajing1126** [comment]
`x86_64`是模拟器的`CPU arch`吧，你打包IPA为什么需要`x86_64`

**Comment by bashen1** [comment]
有一点，模拟器是为了调试方便，这种情况下无法调试，只能真机了
