### ISSUE TITLE
pod install 报错

### ISSUE THREAD

**Issue by CharType** [lujiajing1126/AliyunLogObjc#14]
[!] Unable to satisfy the following requirements:

- `AliyunSlsObjc (~> 1.1.4)` required by `Podfile`

Specs satisfying the `AliyunSlsObjc (~> 1.1.4)` dependency were found, but they required a higher minimum deployment target.

- podfile
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
target 'UITextFIled' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YYKit'
  pod 'SDWebImage','4.3.0'
  pod 'AliyunSlsObjc', '~> 1.1.4'
  # Pods for UITextFIled

end
```

一直出错

**Comment by lujiajing1126** [comment]
更新一下`podspec`試試

Ref. https://guides.cocoapods.org/terminal/commands.html#pod_repo_update

**Comment by Cookiezby** [comment]
是不是现在依赖的库大于8.0导致的，我看现在库里的Podfile是platform :ios, '11.2'

**Comment by lujiajing1126** [comment]
@Cookiezby 你说的有道理，没仔细看上面的话

**Comment by lujiajing1126** [comment]
@CharType 目前版本，尝试一下这个方案

https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod

似乎是我`podspec`配置的问题，之后版本会修改

**Comment by CharType** [comment]
podfile 

```podfile
pod 'AliyunSlsObjc', :git => 'https://github.com/lujiajing1126/AliyunLogObjc.git', :tag => '1.1.4'
```

pod install 之后

```
 $ /bin/bash -c  set -e protoc -I "./AliyunLogObjc"
   --objc_out="./AliyunLogObjc/serde" "./AliyunLogObjc/sls.proto"
   /bin/bash: line 2: protoc: command not found
[!] Failed to download 'AliyunSlsObjc'.
```

**Comment by lujiajing1126** [comment]
安装一下`protobuf`

https://github.com/google/protobuf/issues/3780

**Comment by bboyesc** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SmartPush' do
pod 'AliyunSlsObjc', :git => 'https://github.com/lujiajing1126/AliyunLogObjc.git', :tag => '1.1.4'
end


使用这个 之后
Analyzing dependencies
Pre-downloading: `AliyunSlsObjc` from `https://github.com/lujiajing1126/AliyunLogObjc.git`, tag `1.1.4`
[!] CocoaPods could not find compatible versions for pod "AliyunSlsObjc":
  In Podfile:
    AliyunSlsObjc (from `https://github.com/lujiajing1126/AliyunLogObjc.git`, tag `1.1.4`)

Specs satisfying the `AliyunSlsObjc (from `https://github.com/lujiajing1126/AliyunLogObjc.git`, tag `1.1.4`)` dependency were found, but they required a higher minimum deployment target.

**Comment by bboyesc** [comment]
啥时候更新哟，现在pod 只能11.2可用

**Comment by bboyesc** [comment]
自己通过下载工程，新建一个frameWork工程，pod  platform :ios, '8.0' protobuf依赖库，然后把改项目的代码集成进去，生成一个新的framework，目前可用了。 也许这是个复杂的方法。

**Comment by lujiajing1126** [comment]
@CharType @bboyesc 上传了`1.1.5`，麻烦更新测试一下看看，已经修复`deployment target`的问题
