### ISSUE TITLE
运行不起来 有文件找不到

### ISSUE THREAD

**Issue by lzylzy1991** [lujiajing1126/AliyunLogObjc#18]
<img width="248" alt="74bf50ba03ec10f204c748cc33615f66" src="https://user-images.githubusercontent.com/14507003/40644403-5cce663c-62e0-11e8-8b31-13c6995dfb2e.png">
<img width="187" alt="a13794ff7814b3adf683c3fc28adde0e" src="https://user-images.githubusercontent.com/14507003/40644405-5e21f242-62e0-11e8-9207-c60c8a3bd60d.png">

**Comment by lujiajing1126** [comment]
什么文件没找到？

**Comment by 740629515** [comment]
你们最新的sdk真的不是闹着玩儿的么

**Comment by lujiajing1126** [comment]
@740629515 抱歉这是非官方SDK

如果有问题可以提问，搜索相关的issue，里面都有提到

**Comment by lujiajing1126** [comment]
@lzylzy1991 参考#17
