### ISSUE TITLE
模拟器运行正常，但是到真机上

### ISSUE THREAD

**Issue by sandbeach** [lujiajing1126/AliyunLogObjc#2]
Result: {
errorCode = MissingParameter;
errorMessage = "missing http extend header key : x-log-date";
}

我看了下错误原因，感觉Header中Date字段都被系统过滤了。还有一种原因是Date这个字段格式不对？是不是时间和默认的语言（中文）相关？

**Comment by jhz-libowen** [comment]
dateFormatter.locale = [NSLocale localeWithLocaleIdentifier:@"en_US"];

**Comment by lujiajing1126** [comment]
@sandbeach 已经修复，确实是因为语言问题，我手机是英文，所以没问题。

@jhz-libowen 谢谢，这个方法可以

**Comment by jhz-libowen** [comment]
解决内存泄漏问题：泄漏原因NSURLSession的配置信息的URLCache得不到释放。
解决办法：一>若是存储URL缓存信息
NSString *cachePath = @"AliyunURLCache";
    NSURLCache *cache = [[NSURLCache alloc] initWithMemoryCapacity:16384 diskCapacity:268435456 diskPath:cachePath];
    config.URLCache = cache;
    config.requestCachePolicy = NSURLRequestUseProtocolCachePolicy;
并且在任务结束后加上[session finishTasksAndInvalidate];否则会内存泄漏
二>若是不存储URL缓存信息
NSURLSessionConfiguration换成ephemeralSessionConfiguration
或者NSURLSessionConfiguration在defaultSessionConfiguration的情况下设置config.URLCache = nil;

**Comment by lujiajing1126** [comment]
@jhz-libowen Fixed. see #3
