### ISSUE TITLE
你好，我创建一个新的项目，pod "AliyunSlsObjc"，报错如下

### ISSUE THREAD

**Issue by xyt243135803** [lujiajing1126/AliyunLogObjc#26]
[!] /bin/bash -c 
set -e
protoc -I "./AliyunLogObjc" --objc_out="./AliyunLogObjc/serde" "./AliyunLogObjc/sls.proto"

/bin/bash: line 2: protoc: command not found

**Comment by zhyqieqie** [comment]
已知问题，
https://github.com/lujiajing1126/AliyunLogObjc/issues/17
