### ISSUE TITLE
日志库AliyunSlsObjc在Mac OS 10.15.5，xcode11.5，pod install后报错

### ISSUE THREAD

**Issue by PJStation** [lujiajing1126/AliyunLogObjc#30]
`Unknown type name 'GPB_FINAL'`

**Comment by cuiyu8580** [comment]
@PJStation 你好，请问一下，你这边解决了吗

**Comment by cuiyu8580** [comment]
我看了依赖是3.6.1，总不能本地环境换成3.6.1再去编译吧，两年前的了

**Comment by PJStation** [comment]
> @PJStation 你好，请问一下，你这边解决了吗

未解决，目前是用了以前这个库的替换了一下

**Comment by lujiajing1126** [comment]
Sorry for the inconvenience. I will try to resolve this issue in this week.

**Comment by lujiajing1126** [comment]
A new version `1.2.0` has been released to cocoapods.

Please check the new one. Close this issue now.
