### ISSUE TITLE
这个sdk如何使用

### ISSUE THREAD

**Issue by Kyoooooo** [lujiajing1126/AliyunLogObjc#4]
求sdk下载地址，我下了你的这个demo，导入到了我的工程，但是头文件找不到啊，希望能尽快得到您的回复

**Comment by lujiajing1126** [comment]
```objc
#import <AliyunLogObjc/AliyunLogObjc.h>
```

这个头文件找不到吗？

**Comment by Kyoooooo** [comment]
这个头文件能找到，但是这个文件里面的这三个#import <AliyunLogObjc/Log.h>
#import <AliyunLogObjc/LogGroup.h>
#import <AliyunLogObjc/LogClient.h>找不到

**Comment by Kyoooooo** [comment]
对 就是这个头文件找不到

**Comment by Kyoooooo** [comment]
![a0f943f8-1a85-465a-9968-f00866c3e87c](https://cloud.githubusercontent.com/assets/16569344/21400201/f87cec72-c7e9-11e6-8a32-8a2347ddec4f.png)
我导入工程的就是这些了

**Comment by lujiajing1126** [comment]
额，你需要把这个项目导入，然后`link Framework and Library`

是这样操作的吗

**Comment by Kyoooooo** [comment]
能说的详细一点吗，详细的操作步骤，为啥不支持CocoaPod了

**Comment by Kyoooooo** [comment]
link Framework and Library ，不是太明白这个，求大神指点

**Comment by Kyoooooo** [comment]
大神还在吗，想问一下LogGroup *logGroup = [[LogGroup alloc] initWithTopic: @"" andSource:@""];这里的topic和source应该填什么，稍微试了一下一直提示错误：未能读取数据，因为它的格式不正确。

**Comment by lujiajing1126** [comment]
`topic`是区别你的日志的种类，`source`是区别发送日志方的

**Comment by Kyoooooo** [comment]
一直提示错误：未能读取数据，因为它的格式不正确。如何解决呢

**Comment by Kyoooooo** [comment]
LogClient *client = [[LogClient alloc] initWithApp: kAliyunEndPoint accessKeyID:kAliyunAccessKey accessKeySecret:kAliyunSecretKey projectName:kAliyunbucketName];
    LogGroup *logGroup = [[LogGroup alloc] initWithTopic: @"meterReading" andSource:@"ios"];
    Log *log1 = [[Log alloc] init];
    [log1 PutContent: @"Value" withKey: @"Key"];
    [logGroup PutLog:log1];
    [client PostLog:logGroup logStoreName: @"meterReadingParams" call:^(NSURLResponse* _Nullable response,NSError* _Nullable error) {
        if (error) {
            YWLog(@"%@",error);
        }
    }];

**Comment by lujiajing1126** [comment]
你这个代码能跑起来吗。`log1`和`logGroup`不该都是指针吗
