### ISSUE TITLE
同事集成之后，我这边pull下来报错

### ISSUE THREAD

**Issue by jhz-lilijun** [lujiajing1126/AliyunLogObjc#5]
你好，之前同事在A分支集成的，我pull下来没有问题。后来我把A分支的东西合在了B分支上，B分支忘了提交。 同事那边也把A分支合在了B分支上。 我在B分支 pull 代码的时候 报了如下的错，请问是什么回事呢  ？？

错误信息

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_LogClient", referenced from:
      objc-class-ref in FBaliyunLogTool.o
  "_OBJC_CLASS_$_Log", referenced from:
      objc-class-ref in FBaliyunLogTool.o
      objc-class-ref in FBButeTool.o
      objc-class-ref in FBSaveControlViewController.o
  "_OBJC_CLASS_$_LogGroup", referenced from:
      objc-class-ref in FBaliyunLogTool.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 warnings only

**Comment by lujiajing1126** [comment]
请问你们是如何集成的？

**Comment by jhz-lilijun** [comment]
就是直接把SDK 放在工程里的啊 。

**Comment by jhz-libowen** [comment]
@lujiajing1126 Architectures最好设置成armv7 armv7s arm64,要不然直接编译5和5c不支持运行的
